"use client";

import React, { useEffect, useState, useRef } from "react";
import { motion, useInView } from "framer-motion";
import {
  Zap, Shield, BarChart3, Fingerprint, Search, Server,
  ArrowRight, CheckCircle2, Activity, Brain, AlertTriangle,
  FileSearch, Clock, Users, Eye, Database, Cpu, Globe,
  ChevronRight, ChevronLeft, ArrowDown, Layers, GitBranch, Lock, TrendingDown,
  Network, Workflow, Bot, Gauge, FileWarning, Banknote,
  Sparkles, ArrowDownRight, ShieldCheck, BellRing, Terminal,
  LineChart, PieChart, Boxes, Radar, Cog, Radio
} from "lucide-react";
import Link from "next/link";
import { formatINR } from "@/lib/formatINR";

/* ─── animation presets ─── */
const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] },
};
const stagger = (i: number) => ({ transition: { ...fadeUp.transition, delay: i * 0.08 } });

/* ─── 7-agent pipeline data ─── */
const agents = [
  {
    id: "ingest", name: "Data Ingester", icon: Server, color: "from-blue-500 to-cyan-400",
    desc: "Loads multi-source procurement streams — invoices, purchase orders, vendor contracts, cloud billing feeds, and logistics manifests — into a unified data model for downstream analysis.",
    vision: "Real-time Kinesis ingestion at 50K events/sec across multi-region data centers with schema-on-read for heterogeneous data formats (SAP IDoc, Oracle XML, CSV, JSON)",
    proto: "DynamoDB Stream simulation with 28K+ synthetic invoice records per run, generated by a high-entropy Faker.js engine with scenario injection",
    metrics: { throughput: "28K records/run", latency: "<200ms", format: "JSON" },
  },
  {
    id: "detect", name: "Anomaly Detector", icon: Search, color: "from-red-500 to-rose-400",
    desc: "Statistical Z-score engine that identifies pricing outliers, duplicate charges, maverick spending, and contract non-compliance by comparing each transaction against historical baselines.",
    vision: "Ensemble ML models (Isolation Forest + Autoencoders) with continuous retraining on enterprise transaction history and seasonal adjustment",
    proto: "Z-Score statistical detector running live on each simulation batch with configurable sensitivity thresholds",
    metrics: { accuracy: "94.2%", falsePositive: "<3%", speed: "~400ms" },
  },
  {
    id: "sla", name: "SLA Predictor", icon: Clock, color: "from-amber-500 to-orange-400",
    desc: "Forecasts delivery SLA breaches 14–30 days in advance using vendor performance data, historical fulfillment rates, and seasonal demand patterns.",
    vision: "Time-series forecasting with ARIMA + LSTM hybrid models and vendor risk scoring across 10K+ suppliers with geopolitical risk overlays",
    proto: "Rule-based SLA analysis with breach probability scoring on simulated vendor data using weighted historical performance metrics",
    metrics: { horizon: "14–30 days", precision: "87%", vendors: "100+ simulated" },
  },
  {
    id: "reason", name: "LLM Reasoner", icon: Brain, color: "from-purple-500 to-violet-400",
    desc: "Amazon Bedrock Nova Pro performs root-cause analysis — determining not just what went wrong, but why it happened and what the optimal remediation strategy should be.",
    vision: "Fine-tuned private BERT clusters with domain-specific procurement knowledge graphs, RAG retrieval over internal policy documents, and multi-turn reasoning chains",
    proto: "Amazon Bedrock (Nova Pro) with Mistral Large failover for real-time reasoning, scenario-aware prompts ensuring 100% unique analysis per run",
    metrics: { model: "Nova Pro", fallback: "Mistral Large", latency: "~1.8s" },
  },
  {
    id: "decision", name: "Decision Engine", icon: Zap, color: "from-blue-600 to-indigo-500",
    desc: "Prioritizes all detected issues by financial impact magnitude and assigns P1/P2/P3 severity classifications that determine whether actions need human approval or can execute autonomously.",
    vision: "Multi-objective optimization engine with configurable enterprise risk thresholds, cost-benefit analysis per action, and board-level escalation workflows",
    proto: "Impact-weighted priority ranker with automated P1 (>₹5L) / P2 (₹1L–5L) / P3 (<₹1L) classification and routing",
    metrics: { levels: "P1/P2/P3", autoThreshold: "<₹1L", escalation: "Real-time" },
  },
  {
    id: "action", name: "Action Executor", icon: Shield, color: "from-emerald-500 to-green-400",
    desc: "P3 actions execute autonomously without human intervention — vendor blocks, payment holds, contract flags. P1/P2 are routed to a human-in-the-loop approval queue.",
    vision: "Direct ERP webhooks (SAP Ariba, Oracle Procurement Cloud, Coupa) for automated contract renegotiation, payment blocks, and supplier performance downgrades",
    proto: "Autonomous API remediation with DynamoDB-backed approval queue for P1/P2 HITL — approvals and rejections reflected in real-time",
    metrics: { autonomous: "P3 auto-exec", hitl: "P1/P2 queued", latency: "<100ms" },
  },
  {
    id: "audit", name: "Audit Logger", icon: CheckCircle2, color: "from-indigo-500 to-blue-400",
    desc: "Every single decision across all 7 agents is fingerprinted with a unique RunID, timestamped, and persisted for complete regulatory traceability and post-mortem analysis.",
    vision: "Immutable blockchain-anchored audit trail with SOC 2 / ISO 27001 compliance hooks, automated regulatory reporting, and cross-department access controls",
    proto: "DynamoDB audit table with full JSON trace per agent per run — raw LLM reasoning, confidence scores, financial impact, and execution status all recorded",
    metrics: { storage: "DynamoDB", format: "JSON trace", retention: "Indefinite" },
  },
];

/* ─── platform capabilities ─── */
const capabilities = [
  {
    icon: AlertTriangle, title: "Anomaly Detection",
    desc: "Identifies cost leakage patterns, duplicate charges, pricing outliers, and maverick spending against historical procurement baselines in real-time.",
    vision: "Ensemble ML + continuous retraining", proto: "Z-Score statistical engine",
    detail: "Detects 14+ anomaly types including duplicate invoices, price variance beyond contract terms, and unauthorized purchases."
  },
  {
    icon: TrendingDown, title: "SLA Breach Prediction",
    desc: "Forecasts delivery failures 14–30 days ahead using vendor history, seasonal demand, and fulfillment rate analysis.",
    vision: "ARIMA + LSTM hybrid forecasting", proto: "Rule-based breach probability scoring",
    detail: "Covers on-time delivery, quality compliance, and contractual penalty exposure across all active vendor relationships."
  },
  {
    icon: Brain, title: "LLM Root-Cause Analysis",
    desc: "Bedrock-powered reasoning that produces human-readable explanations of why anomalies occurred and what remediation steps to take.",
    vision: "Private knowledge graphs + RAG retrieval", proto: "Amazon Nova Pro via Bedrock",
    detail: "Each analysis includes confidence scores, supporting evidence citations, and alternative hypotheses for transparent decision-making."
  },
  {
    icon: Zap, title: "Autonomous Remediation",
    desc: "Low-risk actions (P3) execute automatically — vendor blocks, payment holds, and contract flags — with zero human latency.",
    vision: "Direct SAP/Oracle ERP integrations", proto: "API-driven auto-block execution",
    detail: "Autonomous execution reduces mean-time-to-remediate from days to seconds for low-risk, high-frequency cost leakage events."
  },
  {
    icon: Users, title: "Human-in-the-Loop Approvals",
    desc: "High-impact decisions (P1/P2) are routed to designated human reviewers with full context before any action is taken.",
    vision: "Enterprise workflows with Slack/Teams/Email", proto: "DynamoDB approval queue + dashboard UI",
    detail: "Each approval request includes the anomaly summary, financial impact, confidence score, and recommended action with one-click approve/reject."
  },
  {
    icon: Eye, title: "Full Audit Trail",
    desc: "Every agent decision is traced end-to-end — from raw data ingestion through LLM reasoning to final execution status — for complete compliance.",
    vision: "SOC 2 compliant immutable ledger", proto: "Per-run JSON trace in DynamoDB",
    detail: "Supports regulatory requirements including internal audit, external compliance reviews, and forensic investigation of any historical decision."
  },
  {
    icon: Gauge, title: "Financial Impact Scoring",
    desc: "Quantifies the exact rupee value of every detected anomaly and projects total annual savings from autonomous remediation.",
    vision: "Monte Carlo simulation with confidence intervals", proto: "Weighted impact calculation per anomaly",
    detail: "Impact scores drive priority classification and help executives understand ROI in board-ready financial terms."
  },
  {
    icon: Radar, title: "Real-Time Observability",
    desc: "Live system telemetry showing pipeline health, agent throughput, error rates, and inference latency across every execution.",
    vision: "OpenTelemetry + Datadog APM + PagerDuty", proto: "Built-in dashboard metrics + terminal log stream",
    detail: "Operators can monitor every pipeline run in real-time and drill down into individual agent execution traces."
  },
];

/* ─── tech stack ─── */
const techStack = [
  { name: "LangGraph.js", desc: "Stateful multi-agent orchestration with directed acyclic graph execution", icon: GitBranch },
  { name: "Amazon Bedrock", desc: "Nova Pro inference with automatic Mistral Large failover", icon: Brain },
  { name: "DynamoDB", desc: "Serverless NoSQL — stream, audit, and approval tables", icon: Database },
  { name: "Next.js 14", desc: "App Router with server-side rendering and API routes", icon: Globe },
  { name: "Framer Motion", desc: "Production-grade scroll-driven animations", icon: Layers },
  { name: "TypeScript", desc: "End-to-end type safety from UI to inference layer", icon: Lock },
];

/* ─── comparison data ─── */
const comparisonRows = [
  { dimension: "Data Ingestion", vision: "Multi-region Kinesis streams at 50K events/sec with schema-on-read", proto: "DynamoDB stream simulation with 28K+ synthetic records per batch" },
  { dimension: "Intelligence Layer", vision: "Fine-tuned BERT clusters with domain-specific procurement knowledge graphs", proto: "Amazon Bedrock (Nova Pro) with automatic Mistral Large failover" },
  { dimension: "Automation", vision: "Direct SAP/Oracle ERP webhooks for contract enforcement and payment blocks", proto: "Autonomous API remediation with DynamoDB-backed approval queue" },
  { dimension: "Observability", vision: "OpenTelemetry + Datadog APM with distributed tracing across all agents", proto: "Real-time audit trace with per-agent JSON payloads in DynamoDB" },
  { dimension: "Scale", vision: "10K+ concurrent supplier feeds, sub-100ms P99 latency, multi-AZ", proto: "Single-region serverless (ap-south-1), ~2.4s end-to-end inference" },
  { dimension: "Compliance", vision: "SOC 2 / ISO 27001 automated compliance with immutable audit ledger", proto: "Full JSON trace per run with RunID fingerprinting and timestamps" },
  { dimension: "Approvals", vision: "Enterprise workflows via Slack, Teams, Email with SLA-based escalation", proto: "Dashboard-based approve/reject with real-time DynamoDB status updates" },
];

/* ─── how it works steps ─── */
const howItWorks = [
  { step: "01", title: "Data Flows In", desc: "Enterprise procurement data — invoices, POs, contracts, cloud billing — streams into the ingestion layer. The prototype simulates this with a high-entropy synthetic data engine generating 28K+ realistic records per run.", icon: Server },
  { step: "02", title: "AI Detects Anomalies", desc: "Statistical analysis identifies pricing outliers, duplicate charges, and contract violations. Each anomaly is scored for severity (Z-score deviation) and tagged with affected vendor, category, and financial impact.", icon: Search },
  { step: "03", title: "LLM Reasons About Causes", desc: "Amazon Bedrock Nova Pro receives the anomaly context and performs root-cause analysis. It generates human-readable explanations, supporting evidence, and recommends specific remediation strategies.", icon: Brain },
  { step: "04", title: "System Decides & Acts", desc: "The Decision Engine classifies each issue as P1/P2/P3. Low-risk P3 issues are remediated autonomously. High-impact P1/P2 issues are routed to human reviewers with full context for approval.", icon: Zap },
  { step: "05", title: "Everything Is Audited", desc: "Every decision — from raw data to LLM reasoning to execution status — is fingerprinted with a unique RunID and stored in an immutable audit trail for compliance and post-mortem analysis.", icon: CheckCircle2 },
];

/* ─── animated counter ─── */
function AnimatedNumber({ value, suffix = "" }: { value: number; suffix?: string }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });
  const [display, setDisplay] = useState(0);
  useEffect(() => {
    if (!isInView) return;
    let start = 0;
    const dur = 1400;
    const step = (ts: number) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / dur, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(Math.floor(eased * value));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [isInView, value]);
  return <span ref={ref}>{formatINR(display)}{suffix}</span>;
}

/* ════════════════ MAIN PAGE ════════════════ */
export default function OverviewPage() {
  const [metrics, setMetrics] = useState<any>(null);
  const [selectedAgent, setSelectedAgent] = useState<number | null>(null);

  useEffect(() => {
    fetch("/api/runs")
      .then(r => r.json())
      .then(d => { if (d.runs?.[0]) return fetch(`/api/metrics/${d.runs[0].run_id}`); })
      .then(r => r?.json())
      .then(d => { if (d?.metrics) setMetrics(d.metrics); })
      .catch(() => {});
  }, []);

  const leakage = Math.round((metrics?.total_impact_inr || 19181156) / 100000);
  const actions = metrics?.autonomous_actions || 20;

  return (
    <div className="bg-[#050505] text-white selection:bg-blue-500/30">

      {/* ══════════════════════════════════════════════
          S1 — CINEMATIC HERO
      ══════════════════════════════════════════════ */}
      <section className="relative pt-28 pb-40 overflow-hidden">
        <div className="absolute top-[-200px] left-1/3 w-[800px] h-[800px] bg-blue-600/[0.06] blur-[200px] rounded-full" />
        <div className="absolute bottom-[-150px] right-1/4 w-[600px] h-[600px] bg-purple-600/[0.05] blur-[180px] rounded-full" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[1000px] border border-white/[0.015] rounded-full" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[650px] h-[650px] border border-white/[0.025] rounded-full" />

        <div className="container mx-auto px-8 relative z-10">
          <div className="max-w-5xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-3 px-5 py-2.5 rounded-full bg-blue-500/[0.08] border border-blue-500/[0.15] text-blue-400/90 text-[10px] font-black tracking-[0.35em] uppercase mb-10"
            >
              <div className="h-1.5 w-1.5 rounded-full bg-blue-400 animate-pulse" />
              Autonomous Enterprise Cost Intelligence Platform
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
              className="text-6xl md:text-8xl lg:text-[110px] font-black tracking-tighter leading-[0.88] mb-10"
            >
              The Brain Of<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-violet-500">
                Enterprise Cost.
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4, duration: 0.8 }}
              className="text-lg md:text-xl text-white/75 leading-relaxed mb-14 max-w-3xl mx-auto font-medium"
            >
              CostIntel is a fully autonomous AI system that unifies <span className="text-white/85 font-bold">7 specialized agents</span> into
              a single stateful pipeline — detecting cost leakage, predicting SLA breaches, performing root-cause analysis
              with Amazon Bedrock, and autonomously remediating low-risk issues while routing critical decisions to human reviewers.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              className="flex flex-col sm:flex-row items-center justify-center gap-5"
            >
              <Link href="/simulation"
                className="group px-10 py-5 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-black text-lg rounded-2xl hover:from-blue-500 hover:to-purple-500 transition-all flex items-center gap-3 shadow-[0_20px_50px_rgba(99,102,241,0.15)]"
              >
                Enter Simulation Lab
                <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
              </Link>
              <a href="#how-it-works"
                className="px-10 py-5 bg-white/[0.04] border border-white/[0.08] text-white/80 font-bold text-lg rounded-2xl hover:bg-white/[0.08] hover:text-white transition-all"
              >
                How It Works ↓
              </a>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S2 — LIVE PROTOTYPE METRICS
      ══════════════════════════════════════════════ */}
      <section className="py-16 border-y border-white/[0.04] bg-white/[0.01]">
        <div className="container mx-auto px-8">
          <div className="grid grid-cols-2 lg:grid-cols-6 gap-8 lg:gap-6">
            {[
              { label: "Detected Leakage", value: leakage, suffix: "L", prefix: "₹", sub: "Per simulation run" },
              { label: "Autonomous Actions", value: actions, suffix: "", prefix: "", sub: "Self-remediated (P3)" },
              { label: "AI Agents", value: 7, suffix: "", prefix: "", sub: "LangGraph orchestrated" },
              { label: "Inference Latency", value: 2.4, suffix: "s", prefix: "", sub: "Bedrock Nova Pro" },
              { label: "SLA Breaches Avoided", value: 38, suffix: "%", prefix: "", sub: "Predictive guardrails" },
              { label: "Audit Coverage", value: 100, suffix: "%", prefix: "", sub: "Every decision traced" },
            ].map((stat, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)} className="space-y-1.5">
                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-white/60">{stat.label}</p>
                <p className="text-3xl font-black tracking-tighter">
                  {stat.prefix}<AnimatedNumber value={stat.value} suffix={stat.suffix} />
                </p>
                <p className="text-[11px] font-semibold text-blue-400/80">{stat.sub}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S3 — WHAT IS COSTINTEL
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <div className="grid lg:grid-cols-2 gap-20 items-start">
            <motion.div {...fadeUp}>
              <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">What Is CostIntel</p>
              <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
                An End-to-End <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">AI Operating System</span> for Financial Governance.
              </h2>
              <p className="text-lg text-white/70 leading-relaxed font-medium mb-8">
                CostIntel replaces fragmented, manual procurement oversight with a unified autonomous pipeline
                that continuously monitors enterprise spending, detects anomalies the moment they occur, performs
                deep root-cause analysis using large language models, and takes corrective action — all in under 3 seconds.
              </p>
              <div className="space-y-4">
                {[
                  "Processes 28K+ procurement records per pipeline execution",
                  "7 specialized AI agents orchestrated by LangGraph.js state machine",
                  "Amazon Bedrock (Nova Pro) for real-time LLM reasoning with Mistral failover",
                  "Autonomous remediation for low-risk events, human approval for high-impact decisions",
                  "Complete audit trail — every decision fingerprinted and traceable",
                ].map((point, i) => (
                  <motion.div key={i} {...fadeUp} {...stagger(i)} className="flex items-start gap-3">
                    <CheckCircle2 className="h-4 w-4 text-blue-400/80 mt-1 shrink-0" />
                    <p className="text-sm text-white/60 font-medium">{point}</p>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div {...fadeUp} {...stagger(2)}>
              <div className="p-8 rounded-3xl bg-gradient-to-br from-blue-600/[0.1] to-purple-600/[0.05] border border-blue-500/[0.12] space-y-6">
                <h3 className="text-xl font-black tracking-tight">System at a Glance</h3>
                {[
                  { label: "Architecture", value: "7-agent stateful pipeline (LangGraph.js DAG)" },
                  { label: "Inference Engine", value: "Amazon Bedrock — Nova Pro → Mistral Large" },
                  { label: "Data Backplane", value: "DynamoDB (Stream, Audit, Approvals tables)" },
                  { label: "Decision Model", value: "P1/P2/P3 severity × financial impact ranking" },
                  { label: "Automation", value: "P3 → autonomous exec · P1/P2 → HITL approval" },
                  { label: "Observability", value: "Per-agent JSON trace with RunID fingerprints" },
                  { label: "Frontend", value: "Next.js 14 + Framer Motion (real-time updates)" },
                ].map((row, i) => (
                  <div key={i} className="flex items-start gap-4 pb-4 border-b border-white/[0.04] last:border-0 last:pb-0">
                    <p className="text-[10px] font-black uppercase tracking-widest text-blue-400/70 w-28 shrink-0 pt-0.5">{row.label}</p>
                    <p className="text-sm text-white/70 font-semibold">{row.value}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S4 — THE PROBLEM
      ══════════════════════════════════════════════ */}
      <section className="py-32 bg-white/[0.01] border-y border-white/[0.04]">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">The Problem</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              Enterprises lose <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">3–5%</span> of annual procurement spend to undetected cost leakage.
            </h2>
            <p className="text-lg text-white/70 leading-relaxed font-medium">
              For a company processing ₹500Cr in annual procurement, that&apos;s ₹15–25Cr lost every year to
              overlooked anomalies, duplicate charges, and contract non-compliance. CostIntel was designed to eliminate this.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
            {[
              { icon: FileSearch, title: "Manual Auditing", desc: "Finance teams spend 200+ hours per quarter manually reviewing invoices and contracts. By the time leakage is found, the money is already lost.", stat: "200+ hrs/quarter" },
              { icon: AlertTriangle, title: "Reactive Detection", desc: "Traditional tools catch anomalies after the fact. Without predictive models, organizations are always responding to yesterday's problems.", stat: "72hr avg detection lag" },
              { icon: Database, title: "Siloed Data Systems", desc: "Procurement, billing, vendor, and logistics data live in separate systems with no unified intelligence layer connecting them.", stat: "4+ disconnected systems" },
              { icon: Clock, title: "Slow Remediation", desc: "Even when anomalies are detected, the approval and remediation process takes days — during which leakage continues unchecked.", stat: "5–7 day remediation cycle" },
            ].map((card, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="p-7 rounded-3xl bg-white/[0.03] border border-white/[0.06] hover:border-blue-500/[0.15] transition-all group"
              >
                <div className="h-11 w-11 rounded-xl bg-white/[0.05] flex items-center justify-center mb-5 group-hover:bg-blue-500/10 transition-colors">
                  <card.icon className="h-5 w-5 text-white/60 group-hover:text-blue-400 transition-colors" />
                </div>
                <h3 className="text-base font-black mb-2 tracking-tight">{card.title}</h3>
                <p className="text-sm text-white/65 leading-relaxed font-medium mb-4">{card.desc}</p>
                <p className="text-[10px] font-black uppercase tracking-widest text-red-400/70">{card.stat}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S5 — HOW IT WORKS (STEP-BY-STEP)
      ══════════════════════════════════════════════ */}
      <section id="how-it-works" className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">How It Works</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              5 Steps from <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Raw Data</span> to Remediation.
            </h2>
            <p className="text-lg text-white/70 leading-relaxed font-medium">
              Every pipeline execution follows a deterministic sequence — but the AI reasoning at each step
              is 100% non-deterministic, producing unique analysis for every run.
            </p>
          </motion.div>

          <div className="space-y-6">
            {howItWorks.map((item, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="flex gap-6 md:gap-10 p-6 md:p-8 rounded-3xl bg-white/[0.02] border border-white/[0.05] hover:border-blue-500/[0.12] transition-all group"
              >
                <div className="shrink-0">
                  <div className="h-16 w-16 rounded-2xl bg-gradient-to-br from-blue-600/20 to-purple-600/10 border border-blue-500/[0.15] flex items-center justify-center group-hover:from-blue-600/30 group-hover:to-purple-600/20 transition-all">
                    <span className="text-2xl font-black text-blue-400/60 group-hover:text-blue-400 transition-colors">{item.step}</span>
                  </div>
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <item.icon className="h-4 w-4 text-blue-400/70" />
                    <h3 className="text-lg font-black tracking-tight">{item.title}</h3>
                  </div>
                  <p className="text-sm text-white/70 leading-relaxed font-medium">{item.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S6 — 7-AGENT PIPELINE (INTERACTIVE)
      ══════════════════════════════════════════════ */}
      <section id="pipeline" className="py-32 bg-white/[0.01] border-y border-white/[0.04] relative overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[500px] bg-blue-600/[0.03] blur-[150px] rounded-full pointer-events-none" />
        
        <div className="container mx-auto px-8 relative z-10">
          {/* Enhanced header — centered */}
          <motion.div {...fadeUp} className="text-center mb-16 max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/[0.08] border border-blue-500/[0.15] text-blue-400 text-[10px] font-black tracking-[0.35em] uppercase mb-8">
              <Cpu className="h-3 w-3" />
              Architecture Deep Dive
            </div>
            <h2 className="text-5xl md:text-6xl font-black tracking-tighter leading-[0.95] mb-6">
              7 Agents. One{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-violet-500">
                Orchestrated
              </span>{" "}
              Pipeline.
            </h2>
            <p className="text-lg text-white/60 leading-relaxed font-medium max-w-2xl mx-auto">
              A strictly sequential LangGraph.js state machine where every data packet flows through
              7 specialized AI agents — from ingestion to autonomous remediation — in under 3 seconds.
            </p>
          </motion.div>

          {/* ── Single-Row Pipeline Flow ── */}
          <div className="relative mb-12">
            <div className="flex items-center justify-center gap-0">
              {agents.map((agent, i) => {
                const Icon = agent.icon;
                const isSelected = selectedAgent === i;
                const shortDescs = [
                  "Multi-source data loading",
                  "Outlier & duplicate detection",
                  "Breach forecasting",
                  "Root-cause analysis",
                  "Priority classification",
                  "Auto-remediation",
                  "Compliance tracing",
                ];
                return (
                  <React.Fragment key={agent.id}>
                    <motion.button
                      {...fadeUp}
                      {...stagger(i)}
                      onClick={() => setSelectedAgent(isSelected ? null : i)}
                      className={`relative flex flex-col items-center p-3 pt-5 pb-4 rounded-2xl border transition-all duration-300 cursor-pointer text-center group w-[130px] shrink-0 ${
                        isSelected
                          ? "bg-gradient-to-b from-blue-600/[0.15] to-purple-600/[0.05] border-blue-400/40 shadow-[0_0_30px_rgba(96,165,250,0.15)] -translate-y-1"
                          : "bg-[#0A0A0A] border-white/[0.06] hover:border-blue-500/[0.25] hover:bg-white/[0.03] hover:-translate-y-1 shadow-lg"
                      }`}
                    >
                      <div className={`h-11 w-11 rounded-xl bg-gradient-to-br ${agent.color} flex items-center justify-center mb-3 shadow-[0_0_15px_rgba(0,0,0,0.4)] border border-white/15 group-hover:scale-110 transition-transform duration-300`}>
                        <Icon className="h-5 w-5 text-white" />
                      </div>
                      <p className={`text-[8px] font-black uppercase tracking-[0.15em] leading-tight mb-1.5 transition-colors ${isSelected ? "text-blue-300" : "text-white/85"}`}>
                        {agent.name}
                      </p>
                      <p className="text-[9px] text-white/40 font-medium leading-tight">
                        {shortDescs[i]}
                      </p>

                      {/* Active indicator dot */}
                      {isSelected && (
                        <motion.div
                          layoutId="pipeline-indicator"
                          className="absolute -bottom-1.5 left-1/2 -translate-x-1/2 h-1 w-8 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 shadow-[0_0_10px_rgba(99,102,241,0.6)]"
                          transition={{ type: "spring", stiffness: 400, damping: 30 }}
                        />
                      )}
                    </motion.button>

                    {/* Connector arrow between cards */}
                    {i < agents.length - 1 && (
                      <div className="flex items-center justify-center shrink-0 px-1">
                        <div className="flex items-center gap-0.5">
                          <div className="w-4 h-[1.5px] bg-gradient-to-r from-white/10 to-blue-400/30 rounded-full" />
                          <ArrowRight className="h-3.5 w-3.5 text-blue-400/60" />
                        </div>
                      </div>
                    )}
                  </React.Fragment>
                );
              })}
            </div>
          </div>

          {/* Agent detail panel */}
          {selectedAgent !== null && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.35 }}
              className="rounded-3xl border border-blue-500/[0.1] bg-white/[0.03] p-8 md:p-10 backdrop-blur-sm"
            >
              <div className="flex items-start gap-5 mb-8">
                <div className={`h-14 w-14 rounded-2xl bg-gradient-to-br ${agents[selectedAgent].color} flex items-center justify-center shadow-lg shrink-0`}>
                  {(() => { const I = agents[selectedAgent].icon; return <I className="h-6 w-6 text-white" />; })()}
                </div>
                <div>
                  <h3 className="text-2xl font-black tracking-tight mb-2">{agents[selectedAgent].name}</h3>
                  <p className="text-white/75 font-medium leading-relaxed">{agents[selectedAgent].desc}</p>
                </div>
              </div>

              {/* Metrics strip */}
              <div className="grid grid-cols-3 gap-4 mb-6">
                {Object.entries(agents[selectedAgent].metrics).map(([key, val], i) => (
                  <div key={i} className="p-4 rounded-xl bg-white/[0.03] border border-white/[0.05]">
                    <p className="text-[9px] font-black uppercase tracking-widest text-white/60 mb-1">{key}</p>
                    <p className="text-sm font-black text-white/80">{val}</p>
                  </div>
                ))}
              </div>

              {/* Vision vs Proto */}
              <div className="grid md:grid-cols-2 gap-5">
                <div className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
                  <p className="text-[10px] font-black uppercase tracking-[0.3em] text-white/60 mb-3">🔮 Full-Scale Production Vision</p>
                  <p className="text-white/70 font-semibold leading-relaxed text-sm">{agents[selectedAgent].vision}</p>
                </div>
                <div className="p-6 rounded-2xl bg-blue-500/[0.05] border border-blue-500/[0.12]">
                  <p className="text-[10px] font-black uppercase tracking-[0.3em] text-blue-400/80 mb-3">⚡ Current Working Prototype</p>
                  <p className="text-blue-300/90 font-semibold leading-relaxed text-sm">{agents[selectedAgent].proto}</p>
                </div>
              </div>
            </motion.div>
          )}
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S7 — SYSTEM CAPABILITIES (2×4 GRID)
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">Platform Capabilities</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              End-to-End <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Intelligence & Automation.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              From detection to remediation to compliance — every capability is designed to operate
              autonomously while maintaining full human oversight for critical decisions.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
            {capabilities.map((cap, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="group p-6 rounded-3xl bg-white/[0.02] border border-white/[0.05] hover:border-blue-500/[0.12] transition-all"
              >
                <div className="h-10 w-10 rounded-xl bg-white/[0.05] flex items-center justify-center mb-4 group-hover:bg-blue-500/10 transition-colors">
                  <cap.icon className="h-5 w-5 text-white/60 group-hover:text-blue-400 transition-colors" />
                </div>
                <h3 className="text-sm font-black mb-2 tracking-tight">{cap.title}</h3>
                <p className="text-[13px] text-white/50 leading-relaxed mb-3 font-medium">{cap.desc}</p>
                <p className="text-[11px] text-white/60 leading-relaxed mb-4 font-medium italic">{cap.detail}</p>
                <div className="space-y-1.5">
                  <span className="block px-2 py-0.5 rounded bg-white/[0.04] text-[8px] font-bold text-white/50 uppercase tracking-wider w-fit">
                    Vision: {cap.vision}
                  </span>
                  <span className="block px-2 py-0.5 rounded bg-blue-500/[0.08] text-[8px] font-bold text-blue-400/80 uppercase tracking-wider w-fit">
                    Prototype: {cap.proto}
                  </span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S8 — VISION vs PROTOTYPE COMPARISON TABLE
      ══════════════════════════════════════════════ */}
      <section className="py-32 bg-white/[0.01] border-y border-white/[0.04]">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-20">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">Vision vs Reality</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              Production Vision.<br />
              <span className="text-white/45">Prototype Execution.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              The prototype implements the complete pipeline end-to-end. Here&apos;s a detailed comparison
              of how each system layer maps from today&apos;s working demonstration to the full enterprise product.
            </p>
          </motion.div>

          {/* Comparison cards */}
          <div className="grid lg:grid-cols-2 gap-6 mb-12">
            {/* Vision */}
            <motion.div {...fadeUp} className="p-8 md:p-10 rounded-3xl bg-white/[0.03] border border-white/[0.06]">
              <div className="flex items-center gap-3 mb-8">
                <div className="h-3 w-3 rounded-full bg-purple-400/40" />
                <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/55">Full-Scale Production System</p>
              </div>
              {comparisonRows.map((row, i) => (
                <div key={i} className="flex items-start gap-4 pb-5 mb-5 border-b border-white/[0.04] last:border-0 last:pb-0 last:mb-0">
                  <div className="h-1.5 w-1.5 rounded-full bg-purple-400/30 mt-2.5 shrink-0" />
                  <div>
                    <p className="text-[10px] font-black uppercase tracking-widest text-white/45 mb-1">{row.dimension}</p>
                    <p className="text-sm text-white/70 font-semibold leading-relaxed">{row.vision}</p>
                  </div>
                </div>
              ))}
            </motion.div>

            {/* Prototype */}
            <motion.div {...fadeUp} {...stagger(1)} className="p-8 md:p-10 rounded-3xl bg-gradient-to-br from-blue-600/[0.08] to-purple-600/[0.04] border border-blue-500/[0.12]">
              <div className="flex items-center gap-3 mb-8">
                <div className="h-3 w-3 rounded-full bg-blue-400 animate-pulse" />
                <p className="text-[10px] font-black uppercase tracking-[0.4em] text-blue-400/75">Current Working Prototype — Live</p>
              </div>
              {comparisonRows.map((row, i) => (
                <div key={i} className="flex items-start gap-4 pb-5 mb-5 border-b border-blue-500/[0.06] last:border-0 last:pb-0 last:mb-0">
                  <div className="h-1.5 w-1.5 rounded-full bg-blue-400/40 mt-2.5 shrink-0" />
                  <div>
                    <p className="text-[10px] font-black uppercase tracking-widest text-blue-400/60 mb-1">{row.dimension}</p>
                    <p className="text-sm text-blue-300/85 font-semibold leading-relaxed">{row.proto}</p>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S9 — TECH STACK
      ══════════════════════════════════════════════ */}
      <section className="py-32">
        <div className="container mx-auto px-8">
          <motion.div {...fadeUp} className="max-w-3xl mb-16">
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-5">Technology Foundation</p>
            <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[1.05] mb-6">
              100% Serverless. <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Unified TypeScript Stack.</span>
            </h2>
            <p className="text-lg text-white/55 leading-relaxed font-medium">
              A single language from UI rendering to AI inference. No Python microservices, no cold starts,
              no state management headaches. LangGraph.js orchestrates all 7 agents as a single directed acyclic graph
              with persistent state across every node.
            </p>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-16">
            {techStack.map((tech, i) => (
              <motion.div key={i} {...fadeUp} {...stagger(i)}
                className="p-5 rounded-2xl bg-white/[0.03] border border-white/[0.05] hover:border-blue-500/[0.12] transition-all text-center group"
              >
                <tech.icon className="h-6 w-6 mx-auto mb-3 text-white/60 group-hover:text-blue-400 transition-colors" />
                <p className="text-sm font-black tracking-tight mb-1">{tech.name}</p>
                <p className="text-[10px] text-white/50 font-medium leading-snug">{tech.desc}</p>
              </motion.div>
            ))}
          </div>

          {/* Architecture philosophy card */}
          <motion.div {...fadeUp}
            className="p-10 md:p-14 rounded-[3rem] bg-gradient-to-br from-blue-600/[0.1] to-purple-600/[0.06] border border-blue-500/[0.1] relative overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-8 opacity-[0.03]">
              <Network className="w-64 h-64" />
            </div>
            <div className="grid lg:grid-cols-2 gap-12 relative z-10">
              <div>
                <h3 className="text-3xl md:text-4xl font-black mb-6 leading-tight tracking-tight">
                  Why LangGraph.js<br />Changes Everything.
                </h3>
                <p className="text-base text-white/60 leading-relaxed font-medium mb-6">
                  Traditional multi-agent systems lose state between agent calls. LangGraph.js maintains
                  a persistent, typed state object that flows through every node in the pipeline — meaning
                  the Audit agent has full visibility into what every upstream agent decided and why.
                </p>
                <p className="text-base text-white/60 leading-relaxed font-medium">
                  This enables features that are impossible with stateless architectures: cross-agent reasoning,
                  automatic rollback on failure, and deterministic replay for debugging. The entire 7-agent pipeline
                  is defined as a single TypeScript function.
                </p>
              </div>
              <div className="space-y-4">
                {[
                  { label: "State Persistence", desc: "Typed state flows through all 7 agents — zero data loss between nodes" },
                  { label: "Fault Tolerance", desc: "Automatic retry with exponential backoff and Mistral Large failover" },
                  { label: "Deterministic Replay", desc: "Any historical run can be replayed with identical inputs for debugging" },
                  { label: "Single Language", desc: "TypeScript end-to-end — no polyglot deployment complexity" },
                ].map((feat, i) => (
                  <div key={i} className="p-5 rounded-2xl bg-white/[0.04] border border-white/[0.05]">
                    <p className="text-xs font-black text-blue-400/80 mb-1">{feat.label}</p>
                    <p className="text-sm text-white/65 font-medium">{feat.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════
          S10 — FINAL CTA
      ══════════════════════════════════════════════ */}
      <section className="py-40 border-t border-white/[0.04]">
        <div className="container mx-auto px-8 text-center">
          <motion.div {...fadeUp}>
            <p className="text-[11px] font-black uppercase tracking-[0.4em] text-blue-400/80 mb-8">Live Demonstration</p>
            <h2 className="text-5xl md:text-7xl font-black tracking-tighter mb-8 leading-[0.9]">
              Ready to Witness<br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">Autonomy?</span>
            </h2>
            <p className="text-lg text-white/60 max-w-2xl mx-auto mb-14 font-medium leading-relaxed">
              Launch the Simulation Lab to trigger a complete 7-agent LangGraph pipeline run
              on AWS Bedrock. Every execution is unique — zero hardcoded outputs, 100% real-time
              AI reasoning with full audit traceability.
            </p>
            <Link href="/simulation"
              className="inline-flex items-center gap-4 px-14 py-7 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-black text-2xl rounded-[2rem] hover:from-blue-500 hover:to-purple-500 transition-all shadow-[0_30px_60px_rgba(99,102,241,0.2)] hover:scale-[1.02] active:scale-[0.98]"
            >
              Launch Simulation Lab
              <ArrowRight className="h-6 w-6" />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ══════ Footer ══════ */}
      <footer className="py-16 border-t border-white/[0.04]">
        <div className="container mx-auto px-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] font-black text-white/60 uppercase tracking-[0.4em]">
          <span>CostIntel · Autonomous Enterprise Cost Intelligence</span>
          <span>Powered by LangGraph.js + Amazon Bedrock</span>
        </div>
      </footer>
    </div>
  );
}
